# Generated by Django 5.0.6 on 2026-09-10 07:32

import apps.core.utils
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CITIZEN', 'Citizen'), ('STAFF', 'Municipal Staff / Field Officer'), ('MANAGER', 'Department Manager / Ward Head'), ('ADMIN', 'System Administrator')], db_index=True, default='CITIZEN', help_text='Administrative role determining portal interface and access permissions.', max_length=20)),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Primary contact number for SMS updates and notifications.', max_length=20)),
                ('alt_phone', models.CharField(blank=True, help_text='Secondary or emergency contact number.', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Residential or office address.')),
                ('designation', models.CharField(blank=True, help_text='Official job title (e.g. Junior Engineer, Sanitary Inspector, Zonal Commissioner).', max_length=100)),
                ('employee_id', models.CharField(blank=True, help_text='Official municipal employee registration code.', max_length=50, null=True, unique=True)),
                ('is_verified_citizen', models.BooleanField(default=False, help_text='Whether citizen identity has been verified via national ID or utility bill.')),
                ('profile_image', models.ImageField(blank=True, help_text='User avatar / staff identification portrait.', null=True, upload_to=apps.core.utils.sanitize_filename)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
