# Generated by Django 5.0.6 on 2026-09-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveIntegerField(default=1, help_text='Escalation Tier (1=Supervisor, 2=Dept Head, 3=Commissioner)')),
                ('reason', models.CharField(choices=[('SLA_BREACH', 'SLA Target Expired'), ('SLA_APPROACHING', 'SLA Deadline Imminent'), ('CITIZEN_REJECTION', 'Citizen Rejected Inadequate Resolution'), ('PROLONGED_INACTIVITY', 'No Progress for 48+ Hours'), ('MANAGER_OVERRIDE', 'Manager Administrative Intervention'), ('PUBLIC_HAZARD', 'Immediate Hazard / Safety Emergency')], db_index=True, default='SLA_BREACH', max_length=40)),
                ('description', models.TextField(help_text='Detailed justification or root-cause description for escalation')),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_records', to='complaints.complaint')),
                ('escalated_to', models.ForeignKey(blank=True, help_text='Higher officer assigned to review the escalation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_assigned_to_me', to=settings.AUTH_USER_MODEL)),
                ('previous_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_from_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escalation',
                'verbose_name_plural': 'Escalations',
                'ordering': ['-created_at'],
            },
        ),
    ]
