# Generated by Django 5.0.6 on 2026-09-10 07:32

import apps.core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'National Identity Card'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', 'Driving License'), ('UTILITY_BILL', 'Municipal Utility Bill'), ('PROPERTY_TAX', 'Property Tax Receipt')], max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to=apps.core.utils.sanitize_filename)),
                ('status', models.CharField(choices=[('PENDING', 'Verification Pending'), ('VERIFIED', 'Identity Verified'), ('REJECTED', 'Verification Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citizen Verification',
                'verbose_name_plural': 'Citizen Verifications',
            },
        ),
    ]
