# Generated by Django 5.0.6 on 2026-09-10 07:32

import apps.core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.core.utils.sanitize_filename)),
                ('caption', models.CharField(blank=True, help_text='Short description of photo or document', max_length=255)),
                ('stage', models.CharField(choices=[('SUBMISSION', 'Citizen Initial Evidence'), ('BEFORE_WORK', 'Before Work Inspection'), ('DURING_WORK', 'Work In Progress Evidence'), ('AFTER_RESOLUTION', 'Post-Resolution Proof'), ('OFFICIAL_REPORT', 'Technical Departmental Report')], db_index=True, default='SUBMISSION', max_length=30)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('is_internal_only', models.BooleanField(default=False, help_text='If true, visible only to municipal personnel, not citizen.')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
