# Generated by Django 5.0.6 on 2026-09-10 07:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Descriptive policy identifier', max_length=150, unique=True)),
                ('priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical / Emergency')], help_text='Target priority tier.', max_length=20, null=True)),
                ('severity', models.CharField(blank=True, choices=[('MINOR', 'Minor Inconvenience'), ('MODERATE', 'Moderate Civic Issue'), ('SEVERE', 'Severe Disruption'), ('HAZARDOUS', 'Public Hazard / Threat')], help_text='Target severity level.', max_length=20, null=True)),
                ('response_time_hours', models.PositiveIntegerField(default=4, help_text='Required initial review/acknowledgment duration in hours')),
                ('resolution_time_hours', models.PositiveIntegerField(default=48, help_text='Standard deadline to resolve grievance in hours')),
                ('due_soon_threshold_percent', models.PositiveIntegerField(default=75, help_text="Percentage of SLA time elapsed before marking 'Due Soon' (e.g. 75%)")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category scope.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='complaints.category')),
                ('department', models.ForeignKey(blank=True, help_text='Optional department scope. If null, applies globally.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='departments.department')),
            ],
            options={
                'verbose_name': 'SLA Policy',
                'verbose_name_plural': 'SLA Policies',
                'ordering': ['priority', 'resolution_time_hours'],
            },
        ),
        migrations.CreateModel(
            name='SLALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('DUE_SOON', 'Due Soon'), ('BREACHED', 'Breached'), ('MET_WITHIN_SLA', 'Met Within SLA'), ('MET_AFTER_SLA', 'Met After SLA')], db_index=True, default='ON_TRACK', max_length=20)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('actual_hours_taken', models.FloatField(blank=True, null=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_record', to='complaints.complaint')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_complaints', to='sla.slapolicy')),
            ],
            options={
                'verbose_name': 'SLA Log',
                'verbose_name_plural': 'SLA Logs',
                'ordering': ['deadline'],
            },
        ),
    ]
