# Generated by Django 5.0.6 on 2026-09-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Department title', max_length=150, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Short code e.g. PWD, SWM, WSS', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Operational mandate and civic scope')),
                ('email', models.EmailField(blank=True, help_text='Official department desk email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Helpdesk telephone number', max_length=30)),
                ('office_location', models.CharField(blank=True, help_text='Municipal HQ room / office address', max_length=255)),
                ('default_sla_hours', models.PositiveIntegerField(default=48, help_text='Standard baseline SLA duration in hours for this department')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('head_officer', models.ForeignKey(blank=True, help_text='Chief engineer or administrative head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
    ]
