# Generated by Django 5.0.6 on 2026-09-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('CITIZEN_UPDATE', 'Citizen Query / Update'), ('STAFF_REPLY', 'Municipal Staff Response'), ('INTERNAL_NOTE', 'Internal Departmental Note'), ('OFFICIAL_DIRECTIVE', 'Managerial Instruction'), ('SYSTEM_NOTICE', 'Automated System Notice')], db_index=True, default='CITIZEN_UPDATE', max_length=30)),
                ('message', models.TextField()),
                ('is_internal_only', models.BooleanField(db_index=True, default=False, help_text='If true, note is visible only to municipal staff and managers.')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='complaints.complaint')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_complaint_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Message',
                'verbose_name_plural': 'Complaint Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
