# Generated by Django 5.0.6 on 2026-09-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('wards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-exclamation-circle', help_text='FontAwesome or Lucide icon name', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('default_department', models.ForeignKey(help_text='Target department automatically responsible for this category.', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='departments.department')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('default_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical / Emergency')], default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='complaints.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint_number', models.CharField(db_index=True, editable=False, help_text='Unique docket tracking number (CF-YYYYMMDD-XXXX)', max_length=50, unique=True)),
                ('specific_address', models.TextField(help_text='Exact street, house number, or geographic description')),
                ('landmark', models.CharField(blank=True, help_text='Nearby recognizable civic landmark', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude', max_digits=9, null=True)),
                ('title', models.CharField(help_text='Concise summary of the civic grievance', max_length=255)),
                ('description', models.TextField(help_text='Comprehensive details of the problem')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical / Emergency')], db_index=True, default='MEDIUM', max_length=20)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor Inconvenience'), ('MODERATE', 'Moderate Civic Issue'), ('SEVERE', 'Severe Disruption'), ('HAZARDOUS', 'Public Hazard / Threat')], db_index=True, default='MODERATE', max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('ASSIGNED', 'Assigned'), ('INVESTIGATION', 'Investigation'), ('WORK_IN_PROGRESS', 'Work In Progress'), ('RESOLVED', 'Resolved'), ('CITIZEN_VERIFICATION', 'Citizen Verification'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('MORE_INFO_REQUIRED', 'More Information Required'), ('ON_HOLD', 'On Hold'), ('ESCALATED', 'Escalated'), ('REOPENED', 'Reopened')], db_index=True, default='SUBMITTED', max_length=30)),
                ('expected_resolution_date', models.DateTimeField(blank=True, db_index=True, help_text='Target SLA resolution deadline', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when work was marked resolved', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when citizen accepted or docket auto-closed', null=True)),
                ('resolution_summary', models.TextField(blank=True, help_text='Technical explanation of actions taken to resolve the grievance')),
                ('rejection_reason', models.TextField(blank=True, help_text='Administrative justification if rejected or marked duplicate')),
                ('is_escalated', models.BooleanField(db_index=True, default=False, help_text='Whether this complaint has been escalated due to breach or severity')),
                ('escalation_level', models.PositiveIntegerField(default=0, help_text='Current escalation tier (0: Normal, 1: Officer, 2: Manager, 3: Commissioner)')),
                ('reopen_count', models.PositiveIntegerField(default=0, help_text='Number of times reopened by citizen')),
                ('area', models.ForeignKey(blank=True, help_text='Neighborhood locality', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='wards.area')),
                ('assigned_staff', models.ForeignKey(blank=True, help_text='Municipal engineer or inspector currently assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.category')),
                ('citizen', models.ForeignKey(help_text='Citizen who registered this issue', on_delete=django.db.models.deletion.CASCADE, related_name='filed_complaints', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Responsible municipal department', on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='departments.department')),
                ('ward', models.ForeignKey(help_text='Municipal ward where issue is located', on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='wards.ward')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.subcategory')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='complaints__status_4fcfa3_idx'), models.Index(fields=['department', 'status'], name='complaints__departm_77b491_idx'), models.Index(fields=['ward', 'status'], name='complaints__ward_id_d5f4e2_idx')],
            },
        ),
    ]
