# Generated by Django 5.0.6 on 2026-09-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='1 to 5 Star Rating')),
                ('satisfaction', models.CharField(choices=[('VERY_SATISFIED', 'Very Satisfied'), ('SATISFIED', 'Satisfied'), ('NEUTRAL', 'Neutral'), ('DISSATISFIED', 'Dissatisfied'), ('VERY_DISSATISFIED', 'Very Dissatisfied')], default='SATISFIED', max_length=30)),
                ('resolution_accepted', models.BooleanField(default=True, help_text='True if citizen verifies resolution; False if rejected as unsatisfactory')),
                ('comments', models.TextField(blank=True, help_text='Detailed feedback or remarks')),
                ('rejection_reason', models.TextField(blank=True, help_text='Specific grievance if work rejected')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Citizen Feedback',
                'verbose_name_plural': 'Citizen Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
