# Generated by Django 5.0.6 on 2026-09-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, help_text='Instructions, priority rationale, or technical directives')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Acceptance'), ('ACCEPTED', 'Accepted by Staff'), ('REJECTED', 'Rejected / Reassigned'), ('REASSIGNED', 'Reassigned by Manager'), ('COMPLETED', 'Work Completed')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason given by staff if declining assignment')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Manager or administrator who issued this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_assignments', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='complaints.complaint')),
                ('staff', models.ForeignKey(help_text='The field officer or technician assigned to perform the resolution', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Assignment',
                'verbose_name_plural': 'Work Assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
