# Generated by Django 5.0.6 on 2026-09-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, help_text='Standardized action code (e.g. COMPLAINT_CREATED, STATUS_TRANSITION, SLA_BREACHED).', max_length=100)),
                ('target_model', models.CharField(db_index=True, help_text='Name of the affected domain model (e.g. Complaint, Assignment, Escalation).', max_length=100)),
                ('target_id', models.CharField(db_index=True, help_text='Primary key or reference identifier of the affected record.', max_length=100)),
                ('details', models.TextField(blank=True, help_text='Detailed payload, before/after differences, or description of change.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address where the request originated.', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string.', max_length=255)),
                ('actor', models.ForeignKey(blank=True, help_text='User who initiated the action (null if automated system event).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['target_model', 'target_id'], name='audit_audit_target__573821_idx')],
            },
        ),
    ]
